# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='buy_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='actual_gravity',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='expected_gravity',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='start',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='time',
            field=models.DurationField(null=True),
        ),
    ]
