# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_auto_20170902_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='buy_amount',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='note',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='bought_ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beer.BoughtIngredient'),
            preserve_default=False,
        ),
    ]
