# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0004_auto_20171014_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='time',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='beer',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
