# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0006_auto_20171028_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
