# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0007_step_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='bottles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='sold_bottles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(help_text='help', max_length=100),
        ),
    ]
