# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0008_auto_20171109_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='ingredient', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='bought_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beer.BoughtIngredient'),
        ),
    ]
