# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0010_auto_20171112_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtingredient',
            name='waste_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boughtingredient',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boughtingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
