# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0011_auto_20171112_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boughtingredient',
            name='waste_amount',
        ),
        migrations.AddField(
            model_name='boughtingredient',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
