# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0012_auto_20171112_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientBoughtIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bought_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_bought_ingredient', to='beer.BoughtIngredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='bought_ingredient',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='beer.Step'),
        ),
        migrations.AddField(
            model_name='ingredientboughtingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_bought_ingredient', to='beer.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='bought_ingredients',
            field=models.ManyToManyField(related_name='usages', through='beer.IngredientBoughtIngredient', to='beer.BoughtIngredient'),
        ),
    ]
