# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0013_auto_20171115_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'gram'), ('L', 'Liter')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'gram'), ('L', 'Liter')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientboughtingredient',
            name='bought_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_bought_ingredients', to='beer.BoughtIngredient'),
        ),
        migrations.AlterField(
            model_name='ingredientboughtingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_bought_ingredients', to='beer.Ingredient'),
        ),
        migrations.AlterField(
            model_name='step',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='beer.Beer'),
        ),
    ]
