# Generated by Django 2.0.3 on 2018-04-06 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0014_auto_20180215_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beer.Step', verbose_name='next step'),
        ),
    ]
